---
driver:
  forward_agent: yes
  name: vagrant
  customize:
    cpus: 2
    memory: 4096

transport:
  name: winrm

provisioner:
  name: chef_zero_scheduled_task
    
platforms:
  - name: windows2012r2
    driver_config:
      box: windows2012r2
    provisioner:
      require_chef_omnibus: true

suites:
  - name: default
    run_list:
      - recipe[minimal::default]
    attributes: 
        powershell: 
            installation_reboot_mode: "reboot_now"
  - name: powershell5
    run_list:
      - recipe[powershell::powershell5]
    attributes:
