---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  delivery:
    # This needs to run on a Windows host due to the Win32::Registry requirement
    # in ChefSpec
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Install Chef
        uses: actionshub/chef-install@master
      - name: Run Chef Delivery
        run: |
          chef exec delivery local all
        env:
          CHEF_LICENSE: accept-no-persist

  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run yaml Lint
        uses: actionshub/yamllint@master

  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
      - name: Run Markdown Lint
        uses: actionshub/markdownlint@master

  final:
    needs: [delivery, yamllint, mdl]
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@master
